# .github/workflows/test-build.yml
name: 'Test macOS Build'

on:
  workflow_dispatch:  # Manual trigger only
  
jobs:
  test-build:
    name: Test Build for macOS
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile

      - name: Just test the build (no release)
        run: bun run tauri build -- --target aarch64-apple-darwin

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: |
            src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
            src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.app