# .github/workflows/test-build.yml
name: "Test macOS Build"

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-build:
    name: Test Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        # While macos-latest runners are aarch64-apple-darwin,
        # explicitly setting this target here ensures the correct toolchain components are available.
        # It's generally good practice, even if not strictly necessary for host compilation.
        with:
          targets: aarch64-apple-darwin

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile

      - name: Just test the build (no release)
        # IMPORTANT: Removed '-- --target aarch64-apple-darwin'
        # When building natively on a macos-latest (aarch64-apple-darwin) runner,
        # Cargo will place the compiled binary in 'src-tauri/target/release/'.
        # The Tauri bundler expects this default path.
        run: bun run tauri build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          # IMPORTANT: Updated the path to reflect the default release directory
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.app
